# Generated by Django 3.1.4 on 2020-12-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_cards', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('element', models.TextField()),
                ('suit', models.TextField()),
                ('number', models.IntegerField()),
                ('arcanca_rank', models.TextField()),
                ('read_in', models.ManyToManyField(to='tarot.Reading')),
            ],
        ),
    ]
