# Generated by Django 3.1.4 on 2020-12-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='arcanca_rank',
            new_name='arcana_rank',
        ),
    ]
