# Generated by Django 3.1.4 on 2020-12-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0002_auto_20201222_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='arcana_rank',
            new_name='card_arcana_rank',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='element',
            new_name='card_element',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='name',
            new_name='card_name',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='number',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='card',
            old_name='suit',
            new_name='card_suit',
        ),
    ]
