# Generated by Django 3.1.4 on 2020-12-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0003_auto_20201222_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_arcana_rank',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_element',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_suit',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='read_in',
            field=models.ManyToManyField(null=True, to='tarot.Reading'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='num_of_cards',
            field=models.IntegerField(null=True),
        ),
    ]
