# Generated by Django 3.1.4 on 2020-12-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0004_auto_20201222_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='read_in',
        ),
        migrations.AddField(
            model_name='reading',
            name='cards',
            field=models.ManyToManyField(to='tarot.Card'),
        ),
    ]
