# Generated by Django 3.1.4 on 2020-12-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0005_auto_20201222_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='cards',
        ),
        migrations.AddField(
            model_name='card',
            name='readings',
            field=models.ManyToManyField(to='tarot.Reading'),
        ),
    ]
