# Generated by Django 3.1.4 on 2020-12-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0006_auto_20201222_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='readings',
        ),
        migrations.AddField(
            model_name='card',
            name='read_in',
            field=models.ManyToManyField(null=True, to='tarot.Reading'),
        ),
    ]
