# Generated by Django 3.1.4 on 2020-12-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0007_auto_20201222_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='read_in',
        ),
        migrations.AddField(
            model_name='reading',
            name='cards',
            field=models.ManyToManyField(null=True, to='tarot.Card'),
        ),
    ]
