# Generated by Django 3.1.4 on 2020-12-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0008_auto_20201222_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_astro_planet',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_astro_sign',
            field=models.TextField(null=True),
        ),
    ]
