# Generated by Django 3.1.4 on 2020-12-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0009_auto_20201223_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_key_term',
            field=models.TextField(null=True),
        ),
    ]
