# Generated by Django 3.1.4 on 2020-12-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0010_card_card_key_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
