# Generated by Django 3.1.4 on 2021-01-12 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0011_card_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reading',
            name='question',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_image',
            field=models.ImageField(null=True, upload_to='tarot'),
        ),
    ]
