# Generated by Django 3.1.4 on 2021-01-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0012_auto_20210112_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='created_at',
            field=models.DateTimeField(default='2021-01-01 00:00:00'),
        ),
    ]
