# Generated by Django 3.1.4 on 2021-01-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0013_auto_20210112_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
