# Generated by Django 3.1.4 on 2021-01-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0014_auto_20210112_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
