# Generated by Django 3.1.4 on 2021-01-16 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarot', '0016_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tarot.userprofile'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='cards',
            field=models.ManyToManyField(to='tarot.Card'),
        ),
    ]
